### ISSUE TITLE
How to Add Missing Glyphs

### ISSUE THREAD

**Issue by robloo** [unoplatform/uno.fonts#15]
## What would you like to be added:

Several glyphs are still missing. I'm willing to contribute the ones needed on my end but the process to do so is unclear.

How would I go about adding glyphs?

Edit: I see the readme has instructions. However modifying the font directly as a binary means there is no change tracking? How is this reviewed.

## Why is this needed:

To improve coverage with Segoe UI. Specific apps need some missing glyphs.

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [x] Windows
- [ ] Build tasks

**Comment by davidjohnoliver** [comment]
> Edit: I see the readme has instructions. However modifying the font directly as a binary means there is no change tracking? How is this reviewed.

There's no easy way to review binary changes unfortunately, which is one reason why tackling https://github.com/unoplatform/uno.fonts/issues/8 is important.

One thing that's changed since Uno.Fonts was initially packaged is that the Fluent glyphs are now themselves available as a font, which may make it easier to build a fully-automated pipeline to generate the font from a version-controllable text format.

**Comment by robloo** [comment]
Ok, I'm going to have to add several glyphs soon. I guess there is no other option than make the binary changes at the moment. I'll be sure to document here the changes as best as possible.

**Comment by robloo** [comment]
I'm going to actually close this -- at least for now. The decision has been made to switch over entirely to the new Segoe Fluent Icons font available here : https://github.com/microsoft/fluentui-system-icons/blob/master/fonts/FluentSystemIcons-Regular.ttf.

I expect even Uno will start moving in that direction eventually so this issue will just become irrelevant anyway.
